### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by adaurban** [bee-produced/bee-built#5]
Streamline project structure of older modules:
* Consistent naming scheme (`bee`)
* Move functional capabilities to module itself (`@TransactionalResult` should become part of `lib.data`)
* Extensions functions should be placed in packages where the name is of the type which is extended
* AutoConfiguration for Spring Libraries (e.g. EventManager)
* Bump versions

Also provide some minor improvements for `lib.data`:
* Add support for `typedSelection` which was internally in development but is now nearly finished
* Add extension `dfe.toDataSelection()`

**Comment by kurbaniec** [comment]
Was not implemented as no clear benefit was seen:
* Move functional capabilities to module itself (`@TransactionalResult` should become part of `lib.data`)
